In [1]:
# Importación de los datos:
import sklearn
import pandas as pd

# Dataframe
test_data = pd.read_csv("data/public_test.csv")
train_data = pd.read_csv("data/public_train.csv")
test_data.head()
train_data.head()

,ccs,adduct,desc_1,desc_2,desc_3,desc_4,desc_5,desc_6,desc_7,desc_8,...,fgp_611,fgp_612,fgp_613,fgp_614,fgp_615,fgp_616,fgp_617,fgp_618,fgp_619,fgp_620
0,155.71001,Monomer_[M+H],-5.27492,420.85751,0.79886,60.68518,0.22702,54.36304,55.73885,8.28095,...,0,0,1,0,1,1,1,0,1,0
1,179.56000,Monomer_[M-H],-2.00000,1171.97156,1.13333,121.96276,0.15520,100.45390,97.68512,11.36667,...,1,0,0,1,0,1,0,1,1,0
2,180.00000,Monomer_[M+Na],-0.70060,1447.22644,1.30616,141.10509,0.13916,110.47855,108.96603,12.96667,...,0,1,1,0,1,0,0,0,0,1
3,155.53999,Monomer_[M+Na],0.00000,479.80600,0.92774,74.90678,0.21166,65.64590,66.68343,6.83333,...,1,0,1,1,1,0,1,1,0,0
4,173.50000,Monomer_[M+H],-1.63669,978.85028,1.24843,112.27611,0.15789,87.88085,89.68015,10.73333,...,0,1,0,1,0,0,1,0,1,0